#!/bin/bash
case $1 in
	"unlock")
		case $2 in
			"nopass")
				activator send libactivator.system.homebutton
				stouch swipe 50 400 300 400
				echo Device unlocked.
			;;
			*)
				activator send com.bd452.bypass
				echo Device unlocked.
			;;
		esac
		
	;;
	"powerbutton")
		activator send libactivator.system.sleepbutton
		echo Power button press simulated.
	;;
	"home")
		activator send libactivator.system.homebutton
		echo Home button press simulated.
	;;
	"open")
		activator send $2
		echo App opened.
	;;
	"settings")
		activator send libactivator.settings.$2
		echo Preference page opened.
	;;
	"cc")
		activator send libactivator.system.activate-control-center
		echo Control Center opened.
	;;
	"screenshot")
		activator send libactivator.system.take-screenshot
		echo Screenshot saved in gallery.
	;;
	"increase-audio")
		activator send libactivator.audio.increase-volume
		echo Volume increased.
	;;
	"decrease-audio")
		activator send libactivator.audio.decrease-volume
		echo Volume decreased.
	;;
	"increase-brightness")
		activator send libactivator.screen.brightness.increase
		echo Brightness increased.
	;;
	"decrease-brightness")
		activator send libactivator.screen.brightness.decrease
		echo Brightness decreased.
	;;
	"switcher")
		activator send libactivator.system.activate-switcher
		echo Switcher activated.
	;;
	"nc")
		activator send libactivator.system.activate-notification-center
		echo Notification Center opened.
	;;
	"answer-call")
		activator send libactivator.phone.answer-call
		echo Call answered.
	;;
	"decline-call")
		activator send libactivator.phone.disconnect-call
		echo Call declined.
	;;
	"first-homepage")
		activator send libactivator.system.first-springboard-page
		echo First homescreen page opened.
	;;
	"power-menu")
		activator send libactivator.system.power-menu
		echo Power menu opened.
	;;
	"siri")
		activator send libactivator.system.virtual-assistant
		echo Siri opened.
	;;
	"clear-switcher")
		activator send libactivator.system.clear-switcher
		echo App Switcher cleared.
	;;
	"spotlight")
		activator send libactivator.system.spotlight
		echo Spotlight opened.
	;;
	"safe-mode")
		activator send libactivator.system.safemode
		echo Safe mode activated.
	;;
	"powerdown")
		activator send libactivator.system.powerdown
		echo Device turned off.
	;;
	*)
		echo Usage: $0 [ACTION]
		echo List of actions:
		echo unlock - unlock device.
		echo powerbutton - simulate power button press.
		echo home - simulate homebutton press.
		echo open app.bundle.id - open app with specified bundle ID.
		echo settings PreferencePanelName - open specified preference panel in settings.
		echo cc - open Control Center.
		echo screenshot - take a screenshot.
		echo increase or decrease - audio or brightness - increase or decrease audio or brightness - ex. - increase-brightness.
		echo switcher - opens app switcher.
		echo nc - opens Notification Center.
		echo answer or decline - call - answer or decline a call - ex. answer-call.
		echo first-homepage - opens first springboard page.
		echo power-menu - opens the power menu.
		echo siri - opens Siri.
		echo clear-swither - close all apps from the app switcher.
		echo spotlight - opens Spotlight.
		echo safe-mode - launches springboard in safe mode.
		echo powerdown - turns off the device.
	exit 1
esac